# https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources
apiVersion: 1
deleteDatasources:
  - name: MariaDB

datasources:
  - name: MariaDB
    type: mysql
    url: 172.17.0.1:3306
    database: quant
    user: grafana
    secureJsonData:
      password: grafana_password