services:
  quantDatabase:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MYSQL_USER: grafana
      MYSQL_PASSWORD: grafana_password
      MARIADB_DATABASE: 'quant'
    ports:
      - 3306:3306
#     volumes:
#       - quant-db:/var/lib/mysql
# volumes :
#   quant-db:
  grafana:
    build:
      context: ./grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - "GF_DEFAULT_APP_MODE=development"
      - "GF_LOG_LEVEL=debug"
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
